/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import apolloSandbox from "@creazy231/strapi-plugin-apollo-sandbox/strapi-admin";
import cron from "@innovato/strapi-plugin-cron/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import strapiChatgpt from "strapi-chatgpt/strapi-admin";
import entityRelationshipChart from "strapi-plugin-entity-relationship-chart/strapi-admin";
import graphsBuilder from "strapi-plugin-graphs-builder/strapi-admin";
import importExportEntries from "strapi-plugin-import-export-entries/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    "apollo-sandbox": apolloSandbox,
    cron: cron,
    graphql: graphql,
    i18n: i18N,
    "users-permissions": usersPermissions,
    "strapi-chatgpt": strapiChatgpt,
    "entity-relationship-chart": entityRelationshipChart,
    "graphs-builder": graphsBuilder,
    "import-export-entries": importExportEntries,
  },
});
